# Generated by Django 3.2.16 on 2022-12-05 22:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BookCategoryModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Date Joined"
                    ),
                ),
                (
                    "date_modified",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Date Modified"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Book Category Name"),
                ),
            ],
            options={
                "verbose_name": "Book Category",
                "verbose_name_plural": "Book Categories",
            },
        ),
        migrations.CreateModel(
            name="BookModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Date Joined"
                    ),
                ),
                (
                    "date_modified",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Date Modified"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Book Title")),
                (
                    "author",
                    models.CharField(max_length=255, verbose_name="Book Author"),
                ),
                (
                    "publishing_company",
                    models.CharField(
                        max_length=255, verbose_name="Book Publishing Company"
                    ),
                ),
                ("price", models.SmallIntegerField(verbose_name="Book Price")),
                (
                    "page_numbers",
                    models.SmallIntegerField(verbose_name="Book Page Numbers"),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        related_name="books",
                        to="book.BookCategoryModel",
                        verbose_name="Book Categories",
                    ),
                ),
            ],
            options={
                "verbose_name": "Book",
                "verbose_name_plural": "Books",
            },
        ),
    ]
