version: "3.7"
services:
  app:
    build: .
    env_file: .env
    tty: true
    command:
      bash -c 'python manage.py runserver 0.0.0.0:8000'
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  db:
    image: postgres
    healthcheck:
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    env_file:
      - .env
    volumes:
      - my_library_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
    my_library_db:
        external: true
