# Generated by Django 3.2.16 on 2022-12-05 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0001_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="books",
            field=models.ManyToManyField(
                related_name="users", to="book.BookModel", verbose_name="User Books"
            ),
        ),
    ]
